# Generated by Django 3.2.8 on 2021-11-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculaApp', '0003_auto_20211114_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='pessoas_autorizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='controle_saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleSaidaApp.pessoas_autorizadas')),
            ],
        ),
    ]
