# Generated by Django 3.2.8 on 2021-11-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(max_length=50)),
                ('data_nascimento_crianca', models.DateField()),
                ('nome_mae', models.CharField(max_length=50)),
                ('telefone_mae', models.CharField(max_length=15)),
                ('servico_mae', models.CharField(max_length=50)),
                ('telefone_servico_mae', models.CharField(max_length=15)),
                ('nome_pai', models.CharField(max_length=50)),
                ('telefone_pai', models.CharField(max_length=15)),
                ('servico_pai', models.CharField(max_length=50)),
                ('telefone_servico_pai', models.CharField(max_length=15)),
                ('cuidado_medico_observacao', models.CharField(max_length=100)),
                ('cuidado_medico_plano_saude', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pessoas_autorizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='frequencia_mensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor_monitor', models.CharField(max_length=50)),
                ('data_presenca', models.DateField()),
                ('serie', models.CharField(max_length=10)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='controle_saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.pessoas_autorizadas')),
            ],
        ),
    ]
