# Generated by Django 3.2.8 on 2021-11-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmaApp', '0001_initial'),
        ('matriculaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turmaApp.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cuidado_medico_observacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cuidado_medico_plano_saude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='servico_mae',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='servico_pai',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='telefone_servico_mae',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='telefone_servico_pai',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='frequencia_mensal',
        ),
    ]
