# Generated by Django 3.2.8 on 2021-11-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculaApp', '0002_auto_20211113_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bilhete',
        ),
        migrations.RemoveField(
            model_name='pessoas_autorizadas',
            name='crianca',
        ),
        migrations.DeleteModel(
            name='controle_saida',
        ),
        migrations.DeleteModel(
            name='pessoas_autorizadas',
        ),
    ]
